import { lazy, Suspense, useCallback, useEffect, useMemo, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { FiAlertCircle, FiArrowRight, FiBox, FiCalendar, FiFileText, FiLayers, FiPackage, FiRefreshCw, FiShoppingCart, FiTrendingDown } from "react-icons/fi";
import api from "../../utils/api";

const Charts = lazy(() => import("./InventoryCharts"));
const number = new Intl.NumberFormat("id-ID");
const stateClass = { CRITICAL: "bg-red-100 text-red-700", WARNING: "bg-amber-100 text-amber-700", HEALTHY: "bg-emerald-100 text-emerald-700" };
const expiryClass = { EXPIRED: "bg-red-100 text-red-700", TODAY: "bg-orange-100 text-orange-700", D7: "bg-amber-100 text-amber-700", D30: "bg-yellow-100 text-yellow-700", NORMAL: "bg-emerald-100 text-emerald-700" };

function Pager({ pagination, onChange }) {
    if (!pagination || pagination.pages <= 1) return null;
    return <div className="flex items-center justify-between px-5 py-3 text-sm text-gray-500"><span>{pagination.total} records</span><div className="flex gap-2"><button aria-label="Previous page" disabled={pagination.page === 1} onClick={() => onChange(pagination.page - 1)} className="rounded-lg border px-3 py-1 disabled:opacity-40">Previous</button><span className="py-1">{pagination.page}/{pagination.pages}</span><button aria-label="Next page" disabled={pagination.page === pagination.pages} onClick={() => onChange(pagination.page + 1)} className="rounded-lg border px-3 py-1 disabled:opacity-40">Next</button></div></div>;
}

function Overview() {
    const [data, setData] = useState(null); const [error, setError] = useState("");
    const load = useCallback(async () => { try { setError(""); const { data } = await api.get("/inventory-intelligence/overview"); setData(data); } catch { setError("Data inventory belum dapat dimuat. Coba refresh kembali."); } }, []);
    useEffect(() => { load(); }, [load]);
    const cards = data?.cards && [["Active Products", data.cards.totalActiveProducts, FiPackage], ["Active Batches", data.cards.totalActiveBatches, FiLayers], ["Total Inventory", data.cards.totalInventory, FiBox], ["Low Stock", data.cards.lowStockProducts, FiTrendingDown], ["Expired Batches", data.cards.expiredBatches, FiAlertCircle], ["Expiring ≤7 Days", data.cards.expiring7Days, FiCalendar], ["Expiring ≤30 Days", data.cards.expiring30Days, FiCalendar], ["Out of Stock", data.cards.outOfStock, FiShoppingCart]];
    return <div className="space-y-5">
        <header className="flex flex-col gap-3 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-100 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-gray-800">Inventory Intelligence</h1><p className="mt-1 text-sm text-gray-500">Satu layar untuk membaca kondisi batch, stok, dan prioritas operasional.</p></div><button onClick={load} className="inline-flex items-center justify-center gap-2 rounded-xl border border-gray-200 px-4 py-2 text-sm font-medium hover:bg-gray-50"><FiRefreshCw /> Refresh</button></header>
        {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
        {!data ? <div className="rounded-2xl bg-white p-10 text-center text-gray-400">Memuat intelligence inventory…</div> : <>
            <section aria-label="Inventory summary" className="grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(([label, value, Icon]) => <div key={label} className="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-gray-100"><div className="flex items-start justify-between"><span className="text-xs font-medium text-gray-500">{label}</span><Icon className="text-primary" /></div><strong className="mt-3 block text-2xl text-gray-800">{number.format(value)}</strong></div>)}</section>
            <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-100"><div className="flex items-center justify-between"><div><h2 className="font-bold text-gray-800">Today’s Inventory Health</h2><p className="text-xs text-gray-500">Status lintas produk dan batch aktif</p></div><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">{data.health.healthyPercent}% healthy</span></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><Health label="Critical" value={data.health.critical} tone="CRITICAL" /><Health label="Warning" value={data.health.warning} tone="WARNING" /><Health label="Healthy" value={`${data.health.healthyPercent}%`} tone="HEALTHY" /></div><div className="mt-5 flex flex-wrap gap-2"><Link to="/admin/batches" className="rounded-xl bg-primary px-3 py-2 text-sm font-semibold text-white">Open Batch</Link><Link to="/admin/stock" className="rounded-xl border px-3 py-2 text-sm font-semibold text-gray-700">Restock / Stock</Link><Link to="ledger" className="rounded-xl border px-3 py-2 text-sm font-semibold text-gray-700">View Ledger</Link></div></div><NotificationPanel notifications={data.notifications} /></section>
            <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Suspense fallback={<div className="rounded-2xl bg-white p-10 text-center text-gray-400">Loading charts…</div>}><Charts charts={data.charts} /></Suspense><Recommendations items={data.recommendations} /></section>
        </>}
    </div>;
}
const Health = ({ label, value, tone }) => <div className="rounded-xl bg-gray-50 p-3"><strong className={`text-xl ${tone === "CRITICAL" ? "text-red-600" : tone === "WARNING" ? "text-amber-600" : "text-emerald-600"}`}>{value}</strong><span className="block text-xs text-gray-500">{label}</span></div>;
const NotificationPanel = ({ notifications }) => <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-100"><h2 className="font-bold text-gray-800">Notification Center</h2><div className="mt-3 max-h-48 space-y-2 overflow-auto">{notifications.length ? notifications.map((n, i) => <div key={`${n.text}-${i}`} className="rounded-xl bg-gray-50 p-3"><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${stateClass[n.severity]}`}>{n.severity}</span><p className="mt-1 text-sm font-semibold text-gray-700">{n.text}</p><p className="text-xs text-gray-500">{n.reason}</p></div>) : <p className="text-sm text-gray-500">Tidak ada alert inventory.</p>}</div></div>;
const Recommendations = ({ items }) => <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-gray-100"><h2 className="font-bold text-gray-800">Smart Recommendations</h2><div className="mt-3 space-y-3">{items.length ? items.map((item, i) => <div key={`${item.text}-${i}`} className="flex gap-3 rounded-xl border border-gray-100 p-3"><span className={`h-2 w-2 shrink-0 rounded-full mt-1.5 ${item.severity === "CRITICAL" ? "bg-red-500" : "bg-amber-500"}`} /><div className="min-w-0"><p className="text-sm font-semibold text-gray-800">{item.text}</p><p className="text-xs text-gray-500">{item.reason}</p></div></div>) : <p className="text-sm text-emerald-600">Tidak ada tindakan mendesak.</p>}</div></div>;

function Expiry() { return <Monitoring kind="expiry" title="Expired Monitoring" />; }
function LowStock() { return <Monitoring kind="low-stock" title="Low Stock Monitoring" />; }
function Monitoring({ kind, title }) {
    const [rows, setRows] = useState([]), [pagination, setPagination] = useState(), [search, setSearch] = useState(""), [bucket, setBucket] = useState("ALL"), [loading, setLoading] = useState(true);
    const load = useCallback(async (page = 1) => { setLoading(true); try { const { data } = await api.get(`/inventory-intelligence/${kind}`, { params: { page, search, ...(kind === "expiry" ? { bucket } : {}) } }); setRows(data.rows); setPagination(data.pagination); } finally { setLoading(false); } }, [bucket, kind, search]);
    useEffect(() => { const timer = setTimeout(() => load(), 250); return () => clearTimeout(timer); }, [load]);
    return <div className="rounded-2xl bg-white shadow-sm ring-1 ring-gray-100"><header className="border-b p-5"><h1 className="text-2xl font-bold text-gray-800">{title}</h1><p className="mt-1 text-sm text-gray-500">Data batch dan stok aktual, diurutkan berdasarkan prioritas.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input aria-label="Search inventory" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cari produk, SKU, batch, atau cabang" className="rounded-xl border border-gray-200 px-3 py-2 text-sm outline-primary sm:min-w-72" />{kind === "expiry" && <select aria-label="Expiry status filter" value={bucket} onChange={(e) => setBucket(e.target.value)} className="rounded-xl border border-gray-200 px-3 py-2 text-sm"><option value="ALL">All status</option><option value="EXPIRED">Expired</option><option value="TODAY">Expiring today</option><option value="D7">≤ 7 days</option><option value="D30">≤ 30 days</option><option value="NORMAL">Normal</option></select>}</div></header><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-gray-50 text-xs text-gray-500"><tr>{(kind === "expiry" ? ["Product", "Batch", "Expiry", "Days left", "Stock", "Status"] : ["Product", "Branch", "Remaining", "Minimum", "Status"]).map((h) => <th key={h} className="px-5 py-3 font-semibold">{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan="6" className="p-8 text-center text-gray-400">Memuat…</td></tr> : rows.length === 0 ? <tr><td colSpan="6" className="p-8 text-center text-gray-400">Tidak ada data.</td></tr> : rows.map((r) => kind === "expiry" ? <tr key={r._id} className="border-t"><td className="px-5 py-3 font-medium">{r.produk_id.nama_produk}</td><td className="px-5 py-3">{r.batch_number}</td><td className="px-5 py-3">{r.tanggal_expired ? new Date(r.tanggal_expired).toLocaleDateString("id-ID") : "—"}</td><td className="px-5 py-3">{r.daysLeft ?? "—"}</td><td className="px-5 py-3">{number.format(r.stok_saat_ini)}</td><td className="px-5 py-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${expiryClass[r.bucket]}`}>{r.label}</span></td></tr> : <tr key={`${r.product._id}-${r.branch}`} className="border-t"><td className="px-5 py-3 font-medium">{r.product.nama_produk}</td><td className="px-5 py-3">{r.branch}</td><td className="px-5 py-3 font-bold">{number.format(r.remainingStock)}</td><td className="px-5 py-3">{number.format(r.minimumStock)}</td><td className="px-5 py-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${r.remainingStock === 0 ? stateClass.CRITICAL : stateClass.WARNING}`}>{r.remainingStock === 0 ? "Critical" : "Warning"}</span></td></tr>)}</tbody></table></div><Pager pagination={pagination} onChange={load} /></div>;
}

function Ledger() { const [rows, setRows] = useState([]), [pagination, setPagination] = useState(), [search, setSearch] = useState(""); const load = useCallback(async (page = 1) => { const { data } = await api.get("/inventory-intelligence/ledger", { params: { page, search } }); setRows(data.rows); setPagination(data.pagination); }, [search]); useEffect(() => { const t = setTimeout(() => load(), 250); return () => clearTimeout(t); }, [load]); return <div className="rounded-2xl bg-white shadow-sm ring-1 ring-gray-100"><header className="border-b p-5"><h1 className="text-2xl font-bold text-gray-800">Inventory Ledger</h1><p className="mt-1 text-sm text-gray-500">Audit trail dari transaksi dan log mutasi stok yang tersedia.</p><input aria-label="Search ledger" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Cari produk, batch, cabang, tipe" className="mt-4 rounded-xl border border-gray-200 px-3 py-2 text-sm outline-primary" /></header><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-gray-50 text-xs text-gray-500"><tr>{["Date", "Type", "Product", "Batch", "Branch", "User", "Qty", "Before", "After", "Reason"].map((h) => <th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r) => <tr key={r.id} className="border-t"><td className="px-4 py-3 whitespace-nowrap">{new Date(r.date).toLocaleString("id-ID")}</td><td className="px-4 py-3"><span className="rounded bg-sky-50 px-2 py-1 text-xs font-bold text-sky-700">{r.type}</span></td><td className="px-4 py-3 font-medium">{r.product}</td><td className="px-4 py-3">{r.batch}</td><td className="px-4 py-3">{r.branch}</td><td className="px-4 py-3">{r.user}</td><td className="px-4 py-3 font-bold">{r.qty}</td><td className="px-4 py-3">{r.before}</td><td className="px-4 py-3">{r.after}</td><td className="px-4 py-3">{r.reason}</td></tr>)}</tbody></table></div><Pager pagination={pagination} onChange={load} /></div>; }

export default function InventoryIntelligence() { const location = useLocation(); const child = useMemo(() => location.pathname.endsWith("/expiry") ? <Expiry /> : location.pathname.endsWith("/low-stock") ? <LowStock /> : location.pathname.endsWith("/ledger") ? <Ledger /> : <Overview />, [location.pathname]); return <main className="min-h-full bg-background p-4 font-poppins md:p-6">{child}</main>; }
